@echo off
echo Starting GardenVerse AI Backend...
cd backend
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing/Updating dependencies...
pip install -r requirements.txt
echo Starting FastAPI server on port 8000...
uvicorn main:app --reload --port 8000
pause
